examples: silence -Warith-conversion
```
docs/examples/sendrecv.c:58:3: warning: conversion from 'int' to 'unsigned char' may change value [-Warith-conversion]
   58 |   FD_SET(sockfd, &errfd); /* always check for error */
      |   ^~~~~~
docs/examples/sendrecv.c:61:5: warning: conversion from 'int' to 'unsigned char' may change value [-Warith-conversion]
   61 |     FD_SET(sockfd, &infd);
      |     ^~~~~~
docs/examples/sendrecv.c:64:5: warning: conversion from 'int' to 'unsigned char' may change value [-Warith-conversion]
   64 |     FD_SET(sockfd, &outfd);
      |     ^~~~~~
```

need to limit to __DJGPP__ otherwise this happens on other systems:
```
sendrecv.c:54:32: error: unknown warning group '-Warith-conversion', ignored [-Werror,-Wunknown-warning-option]
   54 | #pragma GCC diagnostic ignored "-Warith-conversion"  /* for DJGPP */
      |                                ^
```
https://github.com/curl/curl/actions/runs/11872869922/job/33087089273?pr=15543#step:44:116