tests: add missing MS-DOS header for `delay()`
```
tests/server/util.c: In function 'wait_ms':
tests/server/util.c:247:3: error: implicit declaration of function 'delay' [-Werror=implicit-function-declaration]
  247 |   delay(timeout_ms);
      |   ^~~~~
tests/server/util.c:247:3: warning: nested extern declaration of 'delay' [-Wnested-externs]
```